-- SiteConfig: tambah field statistik landing yg bisa diedit admin
-- (selain alumni — yang auto dari DB count).
-- Idempotent via stored procedure.

DROP PROCEDURE IF EXISTS apply_siteconfig_stat_fields;
DELIMITER //
CREATE PROCEDURE apply_siteconfig_stat_fields()
BEGIN
  IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='SiteConfig' AND COLUMN_NAME='statSiswaValue') THEN
    ALTER TABLE `SiteConfig` ADD COLUMN `statSiswaValue` VARCHAR(191) DEFAULT '1,250+';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='SiteConfig' AND COLUMN_NAME='statSiswaLabel') THEN
    ALTER TABLE `SiteConfig` ADD COLUMN `statSiswaLabel` VARCHAR(191) DEFAULT 'Siswa Aktif';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='SiteConfig' AND COLUMN_NAME='statGuruValue') THEN
    ALTER TABLE `SiteConfig` ADD COLUMN `statGuruValue` VARCHAR(191) DEFAULT '85+';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='SiteConfig' AND COLUMN_NAME='statGuruLabel') THEN
    ALTER TABLE `SiteConfig` ADD COLUMN `statGuruLabel` VARCHAR(191) DEFAULT 'Tenaga Pendidik';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='SiteConfig' AND COLUMN_NAME='statTahunValue') THEN
    ALTER TABLE `SiteConfig` ADD COLUMN `statTahunValue` VARCHAR(191) DEFAULT '2005';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='SiteConfig' AND COLUMN_NAME='statTahunLabel') THEN
    ALTER TABLE `SiteConfig` ADD COLUMN `statTahunLabel` VARCHAR(191) DEFAULT 'Berdiri Sejak';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='SiteConfig' AND COLUMN_NAME='statAlumniLabel') THEN
    ALTER TABLE `SiteConfig` ADD COLUMN `statAlumniLabel` VARCHAR(191) DEFAULT 'Alumni Terdata';
  END IF;
END //
DELIMITER ;
CALL apply_siteconfig_stat_fields();
DROP PROCEDURE apply_siteconfig_stat_fields;
